// <auto-generated />
using System;
using AssetMonitoring.Modules.Telemetry.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetMonitoring.Modules.Telemetry.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetMonitoring.Modules.Telemetry.Domain.Measurements.TelemetryMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("float");

                    b.Property<bool?>("StateValue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Metric", "MeasuredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Measurements_DeviceId_Metric_MeasuredAtUtc");

                    b.ToTable("Measurements", "telemetry", t =>
                        {
                            t.HasCheckConstraint("CK_TelemetryMeasurements_HumidityRange", "[Metric] <> 'Humidity'\r\nOR ([NumericValue] >= 0 AND [NumericValue] <= 100)");

                            t.HasCheckConstraint("CK_TelemetryMeasurements_ValueKind", "(\r\n    [Metric] IN ('Temperature', 'Humidity')\r\n    AND [NumericValue] IS NOT NULL\r\n    AND [StateValue] IS NULL\r\n)\r\nOR\r\n(\r\n    [Metric] IN ('DoorState', 'LightState')\r\n    AND [NumericValue] IS NULL\r\n    AND [StateValue] IS NOT NULL\r\n)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
