name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ci-build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore AssetMonitoring.slnx

      - name: Build solution
        run: dotnet build AssetMonitoring.slnx --configuration Release --no-restore